/*
 * The student mark systems Add Mark UI class that loads up when the add mark 
 * button on the main ui is pressed.
 */
package studentmark;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * @author Heidi Portwine (s6110438)
 */
public class AddMarksUI extends javax.swing.JFrame 
{
    // Variables declared.
    private static ArrayList<Course> courses = new ArrayList();
    static Student student;
    public DefaultComboBoxModel modulesModel = new DefaultComboBoxModel();
    static Course course;
    static Module module;
    
    /**
     * Creates new form AddMarksUI passing through the array list course and student.
     */
    public AddMarksUI(ArrayList<Course> c, Student stu) 
    {
        student = stu;
        courses = c;
        initComponents();
        initComboBox();
        
        // Sets the labels.
        stuLabel2.setText(student.getStudentID());
        fNameLabel2.setText(student.getfName());
        lNameLabel2.setText(student.getlName());
    }
    
    /**
     * Initalises the combo box.
     */
    public void initComboBox()
    {
        // Loops through the courses.
        for(Course c : courses)
        {
            // Checks if the course code is equal to the students course.
            if(c.getCode().equals(student.getCourse()))
            {
                course = c;
                
                // Loops through modules.
                for(Module mod : c.getModule())
                {
                    // Checks if the student does not have marks for the module already.
                    if(!student.getMarks().containsKey(mod.getCode()))
                    {
                        // Adds the module code to the model.
                        module = mod;
                        modulesModel.addElement(mod.getCode());
                    }
                }
            }
        }
        // Sets the module box to dsplay the model.
        moduleBox.setModel(modulesModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        moduleBox = new javax.swing.JComboBox<>();
        moduleLabel = new javax.swing.JLabel();
        markField = new javax.swing.JTextField();
        markLabel = new javax.swing.JLabel();
        stuLabel = new javax.swing.JLabel();
        stuLabel2 = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lNameLabel2 = new javax.swing.JLabel();
        fNameLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        moduleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Module 1", "Module 2", "Module 3", "Module 4" }));

        moduleLabel.setText("Modules:");

        markLabel.setText("Mark:");

        stuLabel.setText("Student ID");

        stuLabel2.setText("studentID");

        fnameLabel.setText("First Name : ");

        jLabel1.setText("Last Name :");

        lNameLabel2.setText("lastName");

        fNameLabel2.setText("firstName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moduleLabel)
                            .addComponent(markLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(markField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stuLabel)
                            .addComponent(jLabel1)
                            .addComponent(fnameLabel))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNameLabel2)
                            .addComponent(lNameLabel2)
                            .addComponent(stuLabel2))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(stuLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stuLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fnameLabel)
                    .addComponent(fNameLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lNameLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduleLabel)
                    .addComponent(moduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markLabel))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(addButton))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The action performed event for the add button on the add marks UI.
     * This will add the users input of mark to the correct module for the student.
     * @param evt 
     */
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        // Sets the variables to get the data from the text field and combo box.
        int m = Integer.parseInt(markField.getText()); 
        String mb = moduleBox.getSelectedItem().toString();
        
        int cIndex = courses.indexOf(course);
        int mIndex = courses.get(cIndex).getModule().indexOf(module);
        int stuIndex = courses.get(cIndex).getStudents().indexOf(student);
        
        // Sets the student number for the course to increase by one student and adds the marks.
        int studNum = courses.get(cIndex).getModule().get(mIndex).getStudentNumber() +1;
        courses.get(cIndex).getModule().get(mIndex).setStudentNumber(studNum);
        courses.get(cIndex).getStudents().get(stuIndex).addModMark(mb, m);
        
        // Displays a message dialog stating that the mark has been added.
        JOptionPane.showMessageDialog(this, "The Mark has been added.");
        // Returns to the main UI.
        StudentMainUI stMain = new StudentMainUI(courses);
        stMain.setVisible(true);
        this.setVisible(false);
               
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * The action performed event for the back button on the add mark UI.
     * This method will take the user back to the main UI screen when the button is pressed.
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        StudentMainUI stMain = new StudentMainUI(courses);
        stMain.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * The main method for the add marks UI.
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMarksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMarksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMarksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMarksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new AddMarksUI(courses, student).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel fNameLabel2;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNameLabel2;
    private javax.swing.JTextField markField;
    private javax.swing.JLabel markLabel;
    private javax.swing.JComboBox<String> moduleBox;
    private javax.swing.JLabel moduleLabel;
    private javax.swing.JLabel stuLabel;
    private javax.swing.JLabel stuLabel2;
    // End of variables declaration//GEN-END:variables
}
